# This file creates a service, allowing the app to communicate
apiVersion: v1
kind: Service
# Name for the service
metadata:
  name: demo-service
# Asign the service with anything matching the label demo-app
spec:
  selector:
    app: demo-app
  # This service will work on tcp, using the port 80 internally but redirecting to 8080 and exposing to 9090
  ports:
    - protocol: TCP
      port: 80  # internal port for this service
      targetPort: 8080  # listening port for the container
      NodePort: 30080    # exposed port to access
  type: NodePort